spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/wiki
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: wiki-db-conn-pool

  liquibase:
    default-schema: wiki

springdoc:
  api-docs:
    path: /api-docs